// <auto-generated>
//   This file was generated from Strings.resx. Add new keys to Strings.resx and
//   add a matching property here. Visual Studio can regenerate this file via the
//   resource editor if the Custom Tool is set to ResXFileCodeGenerator.
// </auto-generated>
using System.Globalization;
using System.Resources;

namespace HexWriter.Web.Resources
{
    public static class Strings
    {
        private static ResourceManager _resourceManager;

        public static ResourceManager ResourceManager
        {
            get
            {
                if (_resourceManager == null)
                    _resourceManager = new ResourceManager("HexWriter.Web.Resources.Strings", typeof(Strings).Assembly);
                return _resourceManager;
            }
        }

        private static string Get(string key)
        {
            return ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
        }

        // ===== Navigation =====
        public static string Nav_Dashboard    { get { return Get("Nav_Dashboard"); } }
        public static string Nav_BookEditor   { get { return Get("Nav_BookEditor"); } }
        public static string Nav_Users        { get { return Get("Nav_Users"); } }
        public static string Nav_Groups       { get { return Get("Nav_Groups"); } }
        public static string Nav_Settings     { get { return Get("Nav_Settings"); } }
        public static string Nav_Logout       { get { return Get("Nav_Logout"); } }
        public static string Nav_Admin        { get { return Get("Nav_Admin"); } }

        // ===== Book Project list =====
        public static string BookProject_Title      { get { return Get("BookProject_Title"); } }
        public static string Btn_CreateNewProject   { get { return Get("Btn_CreateNewProject"); } }
        public static string BookProject_NoCover    { get { return Get("BookProject_NoCover"); } }
        public static string BookProject_NoProjects { get { return Get("BookProject_NoProjects"); } }
        public static string BookProject_CreateFirst{ get { return Get("BookProject_CreateFirst"); } }
        public static string Btn_OpenEditor         { get { return Get("Btn_OpenEditor"); } }
        public static string Btn_ManageFiles        { get { return Get("Btn_ManageFiles"); } }
        public static string Btn_Edit               { get { return Get("Btn_Edit"); } }
        public static string Btn_Export             { get { return Get("Btn_Export"); } }
        public static string Btn_ManageDrafts       { get { return Get("Btn_ManageDrafts"); } }
        public static string Btn_CompareDrafts      { get { return Get("Btn_CompareDrafts"); } }
        public static string Btn_Delete             { get { return Get("Btn_Delete"); } }
        public static string Badge_Editor           { get { return Get("Badge_Editor"); } }
        public static string Badge_ReadOnly         { get { return Get("Badge_ReadOnly"); } }
        public static string Label_LastModified     { get { return Get("Label_LastModified"); } }
        public static string Label_Chapter          { get { return Get("Label_Chapter"); } }
        public static string Label_Chapters         { get { return Get("Label_Chapters"); } }
        public static string Label_Paragraph        { get { return Get("Label_Paragraph"); } }
        public static string Label_Paragraphs       { get { return Get("Label_Paragraphs"); } }
        public static string Confirm_DeleteProject  { get { return Get("Confirm_DeleteProject"); } }

        // ===== Editor =====
        public static string Editor_PanelParagraph      { get { return Get("Editor_PanelParagraph"); } }
        public static string Editor_PanelMeta           { get { return Get("Editor_PanelMeta"); } }
        public static string Editor_PanelNotes          { get { return Get("Editor_PanelNotes"); } }
        public static string Editor_PlaceholderParagraph{ get { return Get("Editor_PlaceholderParagraph"); } }
        public static string Editor_PlaceholderMeta     { get { return Get("Editor_PlaceholderMeta"); } }
        public static string Editor_PlaceholderNotes    { get { return Get("Editor_PlaceholderNotes"); } }
        public static string Editor_SearchPlaceholder   { get { return Get("Editor_SearchPlaceholder"); } }
        public static string Btn_Search                 { get { return Get("Btn_Search"); } }
        public static string Label_WholeWord            { get { return Get("Label_WholeWord"); } }
        public static string Editor_NavFirst            { get { return Get("Editor_NavFirst"); } }
        public static string Editor_NavPrev             { get { return Get("Editor_NavPrev"); } }
        public static string Editor_NavNext             { get { return Get("Editor_NavNext"); } }
        public static string Editor_NavLast             { get { return Get("Editor_NavLast"); } }
        public static string Label_Position             { get { return Get("Label_Position"); } }
        public static string Label_Of                   { get { return Get("Label_Of"); } }
        public static string Label_ChapterNav           { get { return Get("Label_ChapterNav"); } }
        public static string Label_GoTo                 { get { return Get("Label_GoTo"); } }
        public static string Btn_Go                     { get { return Get("Btn_Go"); } }
        public static string Btn_Save                   { get { return Get("Btn_Save"); } }
        public static string Btn_ClearBookmark          { get { return Get("Btn_ClearBookmark"); } }
        public static string Btn_SetBookmark            { get { return Get("Btn_SetBookmark"); } }
        public static string Btn_GoToBookmark           { get { return Get("Btn_GoToBookmark"); } }
        public static string Editor_NoBookmark          { get { return Get("Editor_NoBookmark"); } }
        public static string Btn_InsBefore              { get { return Get("Btn_InsBefore"); } }
        public static string Btn_InsAfter               { get { return Get("Btn_InsAfter"); } }
        public static string Editor_TypeParagraph       { get { return Get("Editor_TypeParagraph"); } }
        public static string Editor_TypeEpigraph        { get { return Get("Editor_TypeEpigraph"); } }
        public static string Btn_Files                  { get { return Get("Btn_Files"); } }
        public static string Confirm_DeleteParagraph    { get { return Get("Confirm_DeleteParagraph"); } }

        // ===== File Upload =====
        public static string FileUpload_SectionUpload    { get { return Get("FileUpload_SectionUpload"); } }
        public static string FileUpload_BookmlPackage    { get { return Get("FileUpload_BookmlPackage"); } }
        public static string FileUpload_LegacyFiles      { get { return Get("FileUpload_LegacyFiles"); } }
        public static string FileUpload_NoLegacyFiles    { get { return Get("FileUpload_NoLegacyFiles"); } }
        public static string FileUpload_ColFilename      { get { return Get("FileUpload_ColFilename"); } }
        public static string FileUpload_ColType          { get { return Get("FileUpload_ColType"); } }
        public static string FileUpload_ColSize          { get { return Get("FileUpload_ColSize"); } }
        public static string FileUpload_ColUploaded      { get { return Get("FileUpload_ColUploaded"); } }
        public static string FileUpload_ColActions       { get { return Get("FileUpload_ColActions"); } }
        public static string FileUpload_ImportLegacyTitle{ get { return Get("FileUpload_ImportLegacyTitle"); } }
        public static string Btn_ImportAllFiles          { get { return Get("Btn_ImportAllFiles"); } }
        public static string Btn_ImportLog               { get { return Get("Btn_ImportLog"); } }
        public static string Btn_BackToProjects          { get { return Get("Btn_BackToProjects"); } }
        public static string Btn_UploadFiles             { get { return Get("Btn_UploadFiles"); } }
        public static string Confirm_DeleteFile          { get { return Get("Confirm_DeleteFile"); } }
        public static string Confirm_ImportFiles         { get { return Get("Confirm_ImportFiles"); } }
    }
}
